name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['26', '27']
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: '3.23'
      - run: epmd -daemon
      - run: rebar3 compile
      - run: rebar3 lint
      - run: rebar3 xref
      - run: rebar3 eunit --cover
      - run: rebar3 cover --verbose
      - run: rebar3 dialyzer
      - run: rebar3 edoc